apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
stringData:
    token: ENC[AES256_GCM,data:+7u2cofw3f9xU+wfvYUBfbv7Xdbbj9Go/njPDIs=,iv:w+tBn7CdjOoSbERJRQyecBKZDrjBBwQb8AmJLspiP+I=,tag:5XkHY47XuIfbGsY1J1MbRw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAram9WdDJXSENrb3dzZGIv
            SUx0K2FPUmVTZHJwSy9mVU5NREN1SHZabkRBCnpyQlNVYkVUSmVaQ1B2QzVEREZ1
            eVA4Yjk0a0pIR0FPZzI5Q2NmeVY3QkkKLS0tIDhSWDFPMkdmamxwbFpKNkh0WmNZ
            My9Uc3dTanJJMFdpK1hKUFBJYVg3bUkKfQfS0FJzghyB+Bcj/bI3dYFQCIklD3d6
            nHaL11IkZbCUlrOI7/8T6Ox0Tu2OtyqxOPP/k+HFadfHDsECIAfCnA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qrwxv75xa4nqeku2cjmwcy2xvsu72ey8cwz4q0dy28s8cd5c6fws4yhp3t
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-12T22:30:39Z"
    mac: ENC[AES256_GCM,data:yAlenlDNHKsOyPiwh+5vKMoRIOAqolDjxSPcWFbPtniMohEqw3ICUAMVKDNiU0il1SbetHgUuFqvk9snemAxx8dahnoOUQ5DOujJqvbAOOmxxhN7BvSMk7o+I9zGUT7d3mra0MF7iEuxxAojRNBR3z7A65g88HdJ5EYtWq5H6UE=,iv:OP2uusSRGf/w4HqaK7+YCVdeM2iB4czKeholOoL7Dqo=,tag:Das6LGBDOmqVk1hZM2yCrA==,type:str]
    version: 3.13.0
