apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
stringData:
    token: ENC[AES256_GCM,data:6FMg2VH9EACzPA9kk+bVwVxpxvid7pAvPOIvWFF1XdbJUMGrsMQHHSMkeswvD4UPSTdPG7k=,iv:Z9M5HUPc4lnBSxpyw48ZlUlqh9N0BdKZteg3WOc6N0s=,tag:viVdhVt2gQlU5H3pDDrrKQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAram9WdDJXSENrb3dzZGIv
            SUx0K2FPUmVTZHJwSy9mVU5NREN1SHZabkRBCnpyQlNVYkVUSmVaQ1B2QzVEREZ1
            eVA4Yjk0a0pIR0FPZzI5Q2NmeVY3QkkKLS0tIDhSWDFPMkdmamxwbFpKNkh0WmNZ
            My9Uc3dTanJJMFdpK1hKUFBJYVg3bUkKfQfS0FJzghyB+Bcj/bI3dYFQCIklD3d6
            nHaL11IkZbCUlrOI7/8T6Ox0Tu2OtyqxOPP/k+HFadfHDsECIAfCnA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qrwxv75xa4nqeku2cjmwcy2xvsu72ey8cwz4q0dy28s8cd5c6fws4yhp3t
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-12T22:33:53Z"
    mac: ENC[AES256_GCM,data:HJPMlNCXhZXYGH/U92CyTm7Irixb1jD9QbNxtkGkNpgHQeD2fxUIPaw483R9EremHS9pt0yfxerhuzeBYthDLDjDWkVntLywNRNOl+L4mR1m5VJ09sm4+NKiHJg6QJ7pOe4Nxusjhlzn726xUixTb9E5brV1N5ofg4x1polSvFY=,iv:yMoBeG5CjWeuoi5IH+u6mk7gLrQxPaI+Rsx8bpqw43A=,tag:3wCPiruokKOCSfdohHCMSw==,type:str]
    version: 3.13.0
