apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: macterm
  namespace: flux-system
spec:
  interval: 5m
  path: ./apps/macterm/manifests
  prune: true
  targetNamespace: macterm
  sourceRef:
    kind: GitRepository
    name: flux-system
