apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-cert-secret
type: Opaque
stringData:
    cert.pem: ENC[AES256_GCM,data:cVLt/CV88/ZIaxXi86NhM9xfKGcwNlZ7+FgkG0bQOz5R5HC6T1NFV49A/C7KPms1dVXcBNJASMyWFtW3akfroZdxl9e9r4n5/wRNyC1J9CQlFy+oXWc2PhDlWSJ8p4vkcGp5Q2/otnxyse6oLsVZMcYO/1bObfdVbw7vzJdjGecUdz54zW6CmNmscnRuMCu1/y/Thqgqz9YneEhxPTBRUS9XS/4xuYMbUsywE81ZZcgcd9knS7eYtmIHAIJb2+oy9yXwo6dqs0zE2SWbJfl8mPds45puScU2AZDCGtyU2JSS+NLu+3yVG1Q+yUk3dv0xxtUfPYSKrs888P9Amji/J6tPs4OBIPh4HbJVtZow5bSt+gv4bek2w9fq,iv:EOS2C3un84p8yBjzPFgF/xgnue5osvi3L+lKsjTWWLc=,tag:EiPDGd13y4NJk5PVG5EH4Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2aEw3QUQxSXNYbDc2T3pj
            ZDJ3YUpDRHVtUUdKa2I4NEtiM243TEdJZ0JnCiswdUVlOGlLNEllS1VYVy9pazhj
            cFQwWkFEeldzVDVvdWJNSy9rV2QrUXMKLS0tIHJxVTFtNkYvZFFjSXFvSWJzdDRF
            eDZjQVhTemllblorMUJpOTV4K3JsZFEK9phkD8lraisCxsKwTSk9W/ngwW+SQDZ8
            pBVRB4c3FSP8U5NBo7LzTF+3qVjmIEV6UbM3S8C/mE50LFCuYeukQQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qrwxv75xa4nqeku2cjmwcy2xvsu72ey8cwz4q0dy28s8cd5c6fws4yhp3t
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-15T22:45:36Z"
    mac: ENC[AES256_GCM,data:Nl8gaUT5FJnBRGakniCxfawXh/U/7Eqk2R/NtTnKSqfdfCqq6nyTq15V6YF2CwI0oIYMMDuaEsJM8bD0f7km86/SrrNL2s7KQdkkD3GGc/0ythmFg2K9XkxV8SgReC1bYJCRLv2WEYgS/KmZgNe0sGsB6HCl/X4Oi1auv8W92UY=,iv:s/y8Gn8ZCl2kVEA2HolJ8FbwdbCVtv4L3vQphrNCB9U=,tag:A87fqbEy1iWG4Jqb18y53Q==,type:str]
    version: 3.13.0
