apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-config-secret
type: Opaque
stringData:
    credentials.json: ENC[AES256_GCM,data:bCLBdJqmYXlt4fdHEmluIAl1m2TPjF7t0OzPEUEvayhIMRAxPh8KV3MkQVjCpZB4q2JcQzsS7EXYklqG5edgHJQjD9Ek24jXiI/UXnFjoKSWkR1Ff2RdXNry1h8H6OKzPCcn60fhz6wPxG0ZUMfhbXlxHbezOC1WWw5jK4sDcDqwg75VL3/O++KgGyzO2XthP9ykBq8BWQiIZKVDo1xCVWkvzJQcLKbrKI/dbQdN854=,iv:BsgyAPJkn/vvgiwVmNes9EwYkgkji59Vj3RbrFBclfI=,tag:OMOiyS0Trmb++++A7yi2qw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0SDFmNFZvMGxlMXJnYkc5
            RDNMeDROalVrVzg0ejdnKy8xT29yVmJGRTFNCnc5elJEeUkvWTlrdDhvQzdhQ3dz
            NWdMRURQL0NwZS9kZnp0b0REWjdPekEKLS0tIFpKLzhmZHE1WDdHOFhnZ3UzQy9j
            L0RZa09hU2JTTXpnOVRNanhlZitlUTgKM9PkRXUQ2tj6YFf+PUcFJFS+89FLf3aJ
            bdYkgsE1tUvcCaxxEs+4vobb8vF9Za2cMh2SBOnBN504tnnRPT+PAg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qrwxv75xa4nqeku2cjmwcy2xvsu72ey8cwz4q0dy28s8cd5c6fws4yhp3t
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-15T22:45:47Z"
    mac: ENC[AES256_GCM,data:Qj5iIpFRrs1geCHsJrZvXjZnPl+uW+y8YQnGE0/gcxI/FvR1ZY4wcXS3Z20u23YPaJh5WgpAKn+7lZ3uU1+J5n+ErAskIXzWLG+UtVHkdd9rYv8Ags+hlLQsPUMsMI89u0+TzULi9jX8NMzwykNF823yk5i4FS9rFk61ttaR9+0=,iv:IZPFEDWSr/pSNDvrlTT1vo11G+YtUpYN49BDypHU07E=,tag:MMN0+3ziNQLgXDxvQ4kYSQ==,type:str]
    version: 3.13.0
