apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-tunnel-token
  namespace: cloudflared
type: Opaque
stringData:
  tunnelToken: ENC[AES256_GCM,data:8I085SSgU77aviaTSfCQBTj/uHRr11Z4NQPah1tOPSHcM7tFosmDS3OyEv15g1X2b7wzHgI5/LBeWrGoTywi0JdOk2CS9KEPcfagPBN/+fWyibum+vdbViZCaATwwbjNwH3qB2ekWReaSU2srdtMupm89t87zNt+Xg2eiakuiWNz7fgxvY8q0kUepcAKiPXy60QOC5REBNVgxkuRzns90yaXBBPqr1IsTi9sZGlkB0iGM891AO0nIg==,iv:r2wAH2oXlFc5Lzf9h9nCOKM23thYf9a1O+HpYrlWIaI=,tag:+WQI0m5ZOntAwPhydSC8lw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOdUk1Y2VXR0EwZ2lWVkNU
        NXlMSVFPWGU5NFhsTjJHWTRzN0p3MFNKQWxBCnlnc2UrN2psWE1lalZCbndvQngr
        dGxUTDZwdnovQ2t4eGR6cXpOMHlnU3cKLS0tIDZXaUgzL0dTYWMvc3hJQitwcVN5
        N0M3aFRnc01CWUtSRHBrajh6dzJPazgKSSGALRxRdL+5thRRKtjW4aUUwBC7wkpz
        SuyqJmOQhrOR3ANZVBxY66uyC4jsxPi2ZEEU6INucFSho6t0gXESJg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qrwxv75xa4nqeku2cjmwcy2xvsu72ey8cwz4q0dy28s8cd5c6fws4yhp3t
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-15T20:26:12Z"
  mac: ENC[AES256_GCM,data:jWOKNQLAoBT7W6BEijl1y9L6j2YJYrZ03YHr9xymBxespOdydpSQXXxuSZM1amcqRxPQD7HUAyo7zknmeuMJQ/PgvtQdO8kNZBdzaMLPdM/DrPIuazCqlrGP+V/Ai/yynGjbklGQK+Rir8eHld/ikV7VHhK7lSXtYYzXDUbRUeQ=,iv:laPK7Pa2+3UGIX49/P7RhlXjMsUA6E44EfzbjrOzzbU=,tag:fDLYMkPtVPTiQzeoJsvgCg==,type:str]
  version: 3.13.0
