apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-tunnel-token
    namespace: cloudflared
stringData:
    token: ENC[AES256_GCM,data:lWnJqHBUE1Ii0Tmsg64HegYYQhj0I6K3aKJCIYLzLywKhTIUBMcbDyPyXslWEOv5HwE6FILL/UU3CDI2EKhEcN6lWmKFbP07Pv11uHFBH3q4MQUpGwV9sAjDmbJmVSAXr3YFvULdXLyLcN4HqT8bnOaB5x4UsK4mCSwd12cAQ/0psNcczXdQOmrjtpLB7wgxxyIBG7CGV2Dm0qEQkA2oWCkf8DLxt1ZequnAZXaRWoQGjyHDkJjKYQ==,iv:ODEHID877PvAW9Qr8lgpJYzLHlAeH0bOclLHYJa+gdY=,tag:/fuA5CwVs7bLmHVz3JNEhQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBScTZRQ3NCUDNWaDFYMFNn
            eDAyWUdBSERoSXo2Qlc5MmUycXpDWWRXVW00CmgxRk5OVXZjK2NiR2pISHAvcFgx
            a2V0d1ZnUi82cWFsUzdxL1F3aUxCMFkKLS0tIHRxWkp1STYrKzZHU0VlTEhBaVdz
            ZW1mWTZkVEVVNDVTZHltUnlNRHJnUGMKigVEX0z1Zok0CSojpB4YT4wGYJPumn0q
            RrpaqxJKbLsneuwwD77WmU7ae3/h9rCQmuDEW4bhs3i2dXxTEM6Rfg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mpfza3ke8r9ud6cylwzx4txarfasn05cadu34az4v426d23tvfgqq6ma37
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-15T19:29:59Z"
    mac: ENC[AES256_GCM,data:z6EZa11de7eZkSmVil+Ln0a6za6aAPAVNY5oRb/RWDIuj0byta6RzVlZ308lsfo8vSqgs+8GeyCnwBzdJd0Ge8lMDLMgBdvNjnTwIqMN+LnewWu3j6XVL5Hz20NCSKjG/GJSF6Y9LBHfooYjTot2Er2OaRzSGkLzmmWNjx8PO/c=,iv:LOEeJEv79Q5/7RhWHcaJvCBbDHnDejbRCXk4u9HPm8s=,tag:YffHAdS8qONlAEpBonjxLw==,type:str]
    version: 3.13.0
