experimental_monorepo_root = true

[settings]
experimental = true

[monorepo]
config_roots = ["bootstrap"]

[env]
_.file = [".env"]
CLUSTER_CIDR = { required = true }
NODE_1_IP_TAILSCALE = { required = true }
NODE_1_IP_ETH = { required = true }
NODE_2_IP_TAILSCALE = { required = true }
NODE_2_IP_ETH = { required = true }

[tools]
cilium-cli = "latest"
kubectl = "latest"
