experimental_monorepo_root = true

[settings]
experimental = true

[monorepo]
config_roots = ["bootstrap", "bootstrap/*"]

[env]
_.file = [".env"]
CLUSTER_CIDR = { required = true }
NODE_1_IP_TAILSCALE = { required = true }
NODE_1_IP_ETH = { required = true }
NODE_2_IP_TAILSCALE = { required = true }
NODE_2_IP_ETH = { required = true }

[tools]
cilium-cli = "latest"
kubectl = "latest"
helm = "latest"
sops = "latest"
age = "latest"
argocd = "latest"

[tasks.up]
description = "Uncordon all nodes and make them schedulable"
run = """
kubectl uncordon node-1 node-2
"""

[tasks.down]
description = "Safely drain all nodes and make them unschedulable"
run = """
kubectl cordon node-1 node-2
kubectl drain node-1 --ignore-daemonsets --delete-emptydir-data
kubectl drain node-2 --ignore-daemonsets --delete-emptydir-data
"""

[tasks.argocd]
description = "Port-forward and open ArgoCD UI in localhost:8080"
run = """
open http://localhost:8080/applications
kubectl port-forward service/argocd-server -n argocd 8080:443
"""
