apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring
  namespace: flux-system
spec:
  interval: 5m
  path: ./apps/monitoring/manifests
  prune: true
  targetNamespace: monitoring
  sourceRef:
    kind: GitRepository
    name: flux-system
