apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: buggyracer
  namespace: flux-system
spec:
  interval: 5m
  path: ./apps/buggyracer/manifests
  prune: true
  targetNamespace: buggyracer
  sourceRef:
    kind: GitRepository
    name: flux-system
