apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./website/ks.yaml
  - ./macterm/ks.yaml
  - ./headlamp/ks.yaml
  - ./cert-manager/ks.yaml
  - ./envoy-gateway/ks.yaml
  - ./networking/ks.yaml
