apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: website
  namespace: website
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  sources:
    - repoURL: https://github.com/thdxg/homelab.git
      targetRevision: main
      path: apps/website
  destination:
    server: https://kubernetes.default.svc
    namespace: website
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
