tunnelConfig:
  name: homelab

tunnelSecrets:
  existingConfigJsonFileSecret:
    name: cloudflared-config-secret
  existingPemFileSecret:
    name: cloudflared-cert-secret

ingress:
  - hostname: taehoonlee.dev
    service: http://cilium-gateway-public-gateway.networking.svc.cluster.local:80
  - hostname: "*.taehoonlee.dev"
    service: http://cilium-gateway-public-gateway.networking.svc.cluster.local:80
  - service: http_status:404

replica:
  count: 2
  allNodes: true
