apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: public-gateway
  namespace: networking
spec:
  gatewayClassName: cilium
  listeners:
    - name: http
      port: 80
      allowedRoutes:
        namespaces:
          from: All
